### ISSUE TITLE
Add speaker bio writing resources

### ISSUE THREAD

**Issue by tbarn** [vmbrasseur/Public_Speaking#10]
I've written a few speaker bios for myself in the past and really struggle with them. I would love to see some resources added that have **helpful tips for writing tech speaker bios**. 

I've searched a bit, but most of the resources I find are very general and don't have tech conferences in mind. 

Thanks for creating this resource! 💖

**Comment by vmbrasseur** [comment]
@tbarn This is such an excellent idea. I haven't seen **any** articles about this (else they'd be in the collection). I'll be on the lookout for them and if nothing else maybe you or I (or both!) could write one.

**Comment by tbarn** [comment]
😄 Even examples of good speaker bios would be awesome! I'm going to be out on the lookout.

**Comment by vmbrasseur** [comment]
K, a section is added now but it only has 2 links so far and I'm not overly thrilled with them. Most of the stuff I found out there was a bunch of content-farmed bullshit.

I probably will write an article about this (probably not this week). The current info out there is not helpful for anyone.
