### ISSUE TITLE
How could we translate the repo?

### ISSUE THREAD

**Issue by airtonzanon** [vmbrasseur/Public_Speaking#21]
I thought to translate this repo do PT-BR because here in Brazil we have so many people who is afraid to speak in public, then I think that this repo will help those people to get ready when they need to do a talk.

But we need to think about structure, how will we do that? 

I thought to create a structure like this:

- CODEOFCONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
  - translations
    - pt-br
      - CODEOFCONDUCT.md
      - CONTRIBUTING.md
      - LICENSE.md
      - README.md
    - es
    - ru
    - ...

But I'm not sure if is the better way.

**Comment by vmbrasseur** [comment]
Generally speaking this looks good. My one concern is the license. Is there an official pt-br version of the CC BY-SA license which can be used? Legal language is too particular to leave to non-lawyers to translate it.

**Comment by airtonzanon** [comment]
Well, I found it at Creative Commons site
pt-br version: https://creativecommons.org/licenses/by-sa/3.0/br/ (translated to English https://creativecommons.org/licenses/by-sa/3.0/br/deed.en)

But we need to think about it, because, if the propose is translate to others languages, maybe it'll be hard to find it in all countries, Don't you think?

**Comment by vmbrasseur** [comment]
It's not our responsibility to translate the license, it's Creative Commons'. If they don't have a translation available for a certain language we can just use the English/International version.

That settled, I'd say this plan is good to go! :-)
