### ISSUE TITLE
Resources in other languages - Chinese

### ISSUE THREAD

**Issue by lisaychuang** [vmbrasseur/Public_Speaking#27]
Hey @vmbrasseur ,

I have some resources in Chinese! Should I add them to current README, or create a new .md file? Let me know how will you like to manage resources in other languages.

Lisa

**Comment by vmbrasseur** [comment]
The supporting docs (explanatory parts of README, contrib, etc) are going to be handled per the suggestion of @airtonzanon in #21. He's just sent a PR (#28) with the first translations, too! Woo! 🎉 

Links to resources other than English, however, should be included directly in the main list. If nothing else, I believe it's very important to have this subtle reminder that there's a lot happening in the world which _isn't in English_. Much of tech forgets that, much to their detriment (IMO).

So your Chinese links can go into the README. Once a few non-English contributions come in I should have a better sense of what I need to review those PRs well, then I'll update the contrib doc accordingly.

Deal?

**Comment by vmbrasseur** [comment]
Hey there, @lisaychuang! Bring on those Chinese resources! We're going to be listing them in the main README along with the rest of the stuff. Yours could be the first non-English resources in the list!

**Comment by lisaychuang** [comment]
Just added 4 links!  ⏩ PR #32

**Comment by vmbrasseur** [comment]
Woo! Thank you!

I'm gonna call this issue closed for now. We can open a new one should other questions arise.
