### ISSUE TITLE
Update contributor guide w/info about non-English resources

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/Public_Speaking#29]
Re: #27 

Once a few PRs for these sorts of resources have come in, I'll have a better idea of what's needed for me to review them properly. I'll update the contrib guide with more information at that point.

**Comment by airtonzanon** [comment]
Hey @vmbrasseur I was thinking to put a tag before the lines (or after, I don't really know haha), but this tag should have the article's language, like:

## General

* [en] [🎥 Speaker Training Workshop](https://archive.org/details/devworld2017-speakertraining) by VM Brasseur
* [pt-br] [Guia para eventos acessíveis: como fazer apresentações (parte I)](https://medium.com/uxconfbr/guia-para-eventos-acessiveis-como-fazer-apresentacoes-parte-i-137317610631) By Talita Pagani
* [en] [speaking.io: Thoughts on public speaking](http://speaking.io/) by Zach Holman
* [pt-br] [Guia para eventos acessíveis: como fazer apresentações (parte II)](https://medium.com/uxconfbr/guia-para-eventos-acess%C3%ADveis-como-fazer-apresenta%C3%A7%C3%B5es-parte-ii-ab84932bd8a2) By Talita Pagani

Above I just put some articles that was wrote in Brazilian Portuguese without sort it as language. But maybe we could order that, like:

## General 
* [en] [🎥 Speaker Training Workshop](https://archive.org/details/devworld2017-speakertraining) by VM Brasseur
* [en] [speaking.io: Thoughts on public speaking](http://speaking.io/) by Zach Holman
* [pt-br] [Guia para eventos acessíveis: como fazer apresentações (parte I)](https://medium.com/uxconfbr/guia-para-eventos-acessiveis-como-fazer-apresentacoes-parte-i-137317610631) By Talita Pagani
* [pt-br] [Guia para eventos acessíveis: como fazer apresentações (parte II)](https://medium.com/uxconfbr/guia-para-eventos-acess%C3%ADveis-como-fazer-apresenta%C3%A7%C3%B5es-parte-ii-ab84932bd8a2) By Talita Pagani

Maybe we can sort the languages as an alphabetical order, so, every time when someone put a new resource there, it should be considered before.

Well, that's just some ideas hehe

**Comment by vmbrasseur** [comment]
@airtonzanon Your thinking is very close to mine! 😀 

I was going to have each non-English article preceded with the emoji of the appropriate flag. (I was just going to add them myself after merging the PRs for now) So the PT-BR entries above would have the Brasilian flag in front of them: 🇧🇷

I wasn't going to have a flag for every single entry since that would become a blur of flags. I'd rather just the non-English ones for now so they really stand out from the list and are attention-grabbing.

What do you think?

**Comment by airtonzanon** [comment]
Wow, that's better than I was thought \o/

**Comment by vmbrasseur** [comment]
I think this one's covered well enough in the contributors guide for now. We can iterate on it later as needed.
