### ISSUE TITLE
Update pt-br CONTRIBUTORS.md 

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/Public_Speaking#30]
Commit 6cf7e070ed7ac923e94911d5ac3c085ed4cac0fe added a little bit of text to the en-us CONTRIBUTORS.md (see diff at that commit).

We should make sure this gets into the pt-br CONTRIBUTORS.md as well.

@airtonzanon? What do you think?

**Comment by airtonzanon** [comment]
Yeah, totally, the changes could be a trouble some times, because we'll need to update the translations.

I can't figure out what we could do to warn all the languages. Did you think how we can solve that?

**Comment by vmbrasseur** [comment]
I can probably handle that on PR review, either asking folks to provide a translation or I can open an issue for someone who knows the language to do so.

As I did here. ;-)

**Comment by airtonzanon** [comment]
Yeah, that will be the best way to do that, we can create a issue and wait for some people who know about the language to traduce it.
