### ISSUE TITLE
Add article about ensuring a good conference program

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/Public_Speaking#58]
I'm not convinced this is the right place for this. Maybe a new conference organising repo is in order?

https://opensource.com/article/18/5/ensuring-high-quality-talks-your-conference

**Comment by anotterdev** [comment]
Maybe https://github.com/stephlocke/awesome-organiser-resources or https://github.com/fromthefront/awesome-how-to-run-events ?

**Comment by vmbrasseur** [comment]
Not appropriate for this repo.
