### ISSUE TITLE
Using correct flag for language/country

### ISSUE THREAD

**Issue by shenjenny** [vmbrasseur/Public_Speaking#68]
Great guide. I'd like to flag that 學術會議英文社交演講技巧 作者：Dr Fiona Hu is by a Taiwanese author, and the language of the post is in Traditional Chinese, not used in China. I'd like to request changing the flag from China to Taiwan so people can know this is in a different language.

**Comment by shenjenny** [comment]
similarly, 18個PPT演講的技巧，讓你的提案能力提高N倍 来源：瘋狂簡報 is also in Traditional Chinese, not used in China. The publication is from Taiwan. Please use the correct flag.

**Comment by penyuan** [comment]
Thanks so much @shenjenny! :smiley: I totally agree this is very important to correct and have submitted a pull request. Hopefully it'll be merged soon!

**Comment by vmbrasseur** [comment]
I'm very grateful that you noticed this and opened an issue, @shenjenny. And huge thanks to @penyuan for the super quick fix!

**Comment by penyuan** [comment]
Splendid! Thanks @vmbrasseur for merging this and for maintaining this awesome list! And thanks @shenjenny for catching it in the first place. :smile:
