### ISSUE TITLE
Newbie Needs Help Adding the Following Resources

### ISSUE THREAD

**Issue by kmcrayton7** [vmbrasseur/Public_Speaking#9]
Every time I think I understand this process, it turns out that I do not. I would like to add the following resources for consideration:

- http://www.codenewbie.org/podcast/the-michael-jordan-of-tech-talks

- https://medium.com/@KimCrayton1/strategies-for-attracting-more-of-the-underrepresented-onto-the-conference-stage-f6d34464f635

**Comment by vmbrasseur** [comment]
All sorted! Thank you for suggesting these!

The second one is really for organisers rather than for speakers, but I included it anyway. 😄

**Comment by kmcrayton7** [comment]
Thank you!

**Comment by vmbrasseur** [comment]
❤️
